# -*- coding: utf-8 -*-
"""class 3 visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tANMlHWV09ZNCIJq-RZ2_NOVxX_VUT4S
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

np.random.seed(613)
x=np.arange(50)
y1=np.random.randint(0,100,50)
y2=np.random.randint(0,100,50)

#plot
fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y1)
ax.plot(x,y2)



#adding a legend
fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y1,label='person1')
ax.plot(x,y2,label='person2')
ax.legend(loc="lower right",
          frameon=True,
          fontsize=12,
          ncol=2,
          shadow=True)

#moving legend outside
fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y1,label='person1')
ax.plot(x,y2,label='person2')
ax.legend(loc="upper left",
          bbox_to_anchor=(1,1))

# bbox_to_anchor=(1,1))

#moving legend outside- lower left
fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y1,label='person1')
ax.plot(x,y2,label='person2')
ax.legend(loc="upper right",
          bbox_to_anchor=(1,0.5))

# The second value, 0.5, represents the y-coordinate and is also in the range [0, 1], where 0 is the bottom edge of the axes and 1 is the top edge. A value of 0.5 means it is centered vertically.

fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y1,label='person1')
ax.scatter(x,y2,label='person2')
ax.legend(loc="lower right")
ax.text(10,95,"this value is important")

fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y1,label='person1')
ax.scatter(x,y2,label='person2')
ax.legend(loc="lower right")
ax.text(10,125,"some random words!",
        ha="center",
        color="red",
        size=20)
#10,95 changed to 10,125

#positioning text annotation
fig,ax=plt.subplots()
ax.axis([0,10,0,10])

ax.text(1,5,"data:(1,5)",transform=ax.transData)
ax.text(0.5,0.1,"axes:(0.5,0.1)",transform=ax.transAxes)
ax.text(0.2,0.2,"figure:(0.2,0.2)",transform=fig.transFigure)

#annotation with arrows
fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y1,label='person1')
ax.scatter(x,y2,label='person2')
ax.legend(loc="lower right")
ax.annotate("this is imporatnt!",xy=(10,95),xytext=(20,94),
            arrowprops=dict(facecolor="black",
                             shrink=0.05))
fig.show()

#annotation with arrows
fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y1,label='person1')
ax.scatter(x,y2,label='person2')
ax.legend(loc="lower right")
ax.annotate("this is imporatnt!",xy=(10,95),xytext=(20,94),
            arrowprops=dict(arrowstyle ="wedge",
                             color="hotpink"))
fig.show() #arrowstyple has to be lowercase

fig,ax=plt.subplots(figsize = (5,3))
ax.scatter(x,y1,label = "Person 1")
ax.scatter(x,y2,label = "Person 2")
ax.legend(loc='lower right')
ax.xaxis.set_major_locator(plt.MaxNLocator(3))

fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y1,label='person1')
ax.scatter(x,y2,label='person2')
ax.legend(loc="lower right")
plt.xticks(rotation=45,ha="right",fontsize=12,font="serif") # corrected function name

fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y1,label='person1')
ax.scatter(x,y2,label='person2')
ax.legend(loc="lower right")
font1={"family":"serif","color":"indigo"}
plt.xlabel("Shiny New X axis!",fontsize=18,fontdict=font1)

plt.style.available

plt.style.use("classic")
fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y1)

plt.style.use("ggplot")
np.random.seed(613)
x1=np.arange(50)
y1=np.random.randint(0,75,50)
x2=np.array(["Luffy","Zoro","Nami","Usopp","Sanji"])
y2=np.array([110,180,240,90,220])


fig,(ax1,ax2)=plt.subplots(ncols=2,
                           nrows=1,figsize=(7,3))
ax1.scatter(x1,y1)
ax2.bar(x2,y2)

fig,(ax1,ax2)=plt.subplots(ncols=2,
                           nrows=1,figsize=(9,3))
font1={"family":"serif","size":14}
ax1.scatter(x1,y1,marker="o",color="red")
ax2.bar(x2,y2,color="darkgreen")
ax1.set_title("Scatter Plot",fontdict=font1)
ax2.set_title("Bar Plot",fontdict=font1)

fig,someaxes=plt.subplot_mosaic([['ax1','ax3'],['ax2','ax3']],figsize=(7,4))
someaxes["ax1"].scatter(x1,y1)
someaxes["ax2"].bar(x2,y2)
someaxes["ax3"].plot(x1,y1)

#where is big label

fig,someaxes=plt.subplot_mosaic([['ax1','ax3'],['ax2','ax3']],figsize=(10,15))
someaxes["ax1"].scatter(x1,y1)
someaxes["ax2"].bar(x2,y2)
someaxes["ax3"].plot(x1,y1)
someaxes["ax1"].set_xlabel("A big label",fontsize=25)
someaxes["ax2"].set_xlabel("another label",fontsize=18)
someaxes["ax3"].set_xlabel("Label2: fast 2 furious",fontsize=18)

x=np.array(["Luffy","Zoro","Nami","Usopp","Sanji"])
y1=np.array([110,180,240,90,220])
y2=np.array([170,100,120,90,50])
fig,ax=plt.subplots(figsize=(7,3))
ax.bar(x,y1,color="indigo")
ax.plot(x,y2,color="red")

#add error information
y2_sd=np.std(y2)
fig,ax=plt.subplots(figsize=(7,3))
ax.plot(x,y2,color="red")
ax.errorbar(x,y2,
            yerr=y2_sd,
            fmt="none",
            ecolor="red",
            elinewidth=3,
            capthick=3,
            capsize=10
            )