# -*- coding: utf-8 -*-
"""july30th data visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yATHxIWkM7sxdQg9MD6hDnIV4XnO20pc
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
import requests
from io import BytesIO

response = requests.get('https://upload.wikimedia.org/wikipedia/en/c/cb/Monkey_D_Luffy.png')
image_file = BytesIO(response.content)
image = Image.open(image_file)

x=np.array(["Luffy", "Zoro", "Nami", "Usopp", "Sanji"])
y2 = np.array([170,100,90,120,50])

fig, ax = plt.subplots (figsize=(7,3))
ax.plot(x,y2, color = "red")
ax_image = fig.add_axes([0.1, #x coordinate
0.11,
0.15,  0.35]) #image height

#show image
ax_image.imshow(image)
ax_image.axis('off')

