# -*- coding: utf-8 -*-
"""july31 visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjX9_knOxXWSwC3FxlUR6-flbORF1J3Z
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests

tips=sns.load_dataset('tips')
print(tips)

sns.set_style('white')
sns.lineplot(data=tips,x='total_bill',y='tip')
#

tipgraph=sns.lineplot(data=tips,x='total_bill',y='tip')
tipgraph.set(title='Total Bill vs Tip')
tipgraph.set(xlabel='Total Bill($)')
tipgraph.set(ylabel='Tip amount($)')
#

fig=plt.subplots(figsize=(10,3))
tipgraph=sns.lineplot(data=tips,
                      x='total_bill',
                      y='tip',color="hotpink",linestyle="--",linewidth=3,marker='o',markerfacecolor="indigo")
tipgraph.set(title='Tips vs Total Bill')
tipgraph.set(xlabel='Total Bill($)')
tipgraph.set(ylabel='Tip amount($)')
#

fig, ax = plt.subplots(figsize=(10,3)) # Changed to create fig and ax objects
tipgraph=sns.lineplot(data=tips,
                      x='total_bill',
                      y='tip',
                      color="hotpink",
                      linestyle="--",
                      linewidth=3,
                      marker='o',
                      markeredgecolor="indigo") # Changed markercolor to markeredgecolor
tipgraph.set(title='Tips vs Total Bill')
tipgraph.set(xlabel='Total Bill($)')
tipgraph.set(ylabel='Tip amount($)')
plt.show() # Added to display the plot

tipgraph=sns.scatterplot(data=tips,x='total_bill',y='tip',style='time',hue='day',palette=["yellow","hotpink","indigo"])
tipgraph.set(title='Tips vs Total Bill',xlabel='Total Bill($)',ylabel='Tip amount($)')
#

sns.pairplot(data=tips,hue='day')
#

!pip install seaborn
import seaborn as sns

tipgraph=sns.relplot(data=tips,
           x="total_bill",  # Corrected column name
           y="tip",
           hue="sex",
           col="day",
           kind="scatter",
           col_wrap=4 ) #four pictures in a row
plt.show()

import plotly.graph_objects as go
x1=np.array(["zoro","Luffy","Nami","Sanji","Usopp"])
y1=np.array([110,180,240,99,220])

graph=go.Figure()
graph.add_trace(go.Bar(x=x1,y=y1))
graph.update_layout(title="pirate Scores",
                   xaxis_title="Pirates",
                   yaxis_title="Scores")

graph=go.Figure()
graph.add_trace(go.Scatter(x=x1,
                           y=y1,
                           mode="markers",
                           marker=dict(size=15,
                                       color="hotpink",
                                       opacity=1,
                                       line=dict(width=5,color="purple"))))
graph.update_layout(title="interactive pirate plots",
                   xaxis_title="Pirates",
                   yaxis_title="Scores",
                    width=500,
                    height=500)



!pip install wordcloud
from wordcloud import WordCloud

df=pd.read_csv("https://raw.githubusercontent.com/prasertcbs/basic-dataset/master/movie_quotes.csv",
               on_bad_lines='skip')
df

text=" ".join([each for each in df.quote])
wordcloud=WordCloud(background_color="white",colormap="inferno").generate(text)
fig,ax=plt.subplots(figsize=(7,3))
ax.imshow(wordcloud,interpolation="bilinear")
ax.axis("off")

!pip install matplotlib-venn
from matplotlib_venn import venn2,venn2_circles,venn2_unweighted

A=set(["apple","banana","watermelon"])
B=set(["pumpkin","blueberry","apple","key lime"])

diagram=venn2([A,B],set_labels=("Fruits","Pies"),
              set_colors=("blue","red"),alpha=0.5)
diagram.get_label_by_id("10").set_text("\n".join(A-B))
diagram.get_label_by_id("11").set_text("\n".join(A & B))
diagram.get_label_by_id("01").set_text("\n".join(B-A))
#