# -*- coding: utf-8 -*-
"""visualization class2- update with comments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfYTi53G0NomCJHR0yGsrNljMPkPh69j
"""

#import all the libaray we need

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests

# making up some data to do visulization
np.random.seed(613)#set the random seed so the result is reproducible
x=np.arange(50) #create 50 intergars for x axis
y=np.random.randint(0,100,50) #create 50 integer for y axis
fig,ax=plt.subplots(figsize=(5,3))# the plot created should be with a specific size (5 inches by 3 inches)
ax.scatter(x,y)# draw scatter plot

fig,ax=plt.subplots(figsize=(5,3))
ax.barh(x,y)# used horizontal bars
ax.bar(x,y)#vertical

# for here I darw two and figure out they will be show in one picture

#now we draw a line plot
fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y)

#now we draw a hist plot

fig,ax=plt.subplots(figsize=(5,3))
ax.hist(y)

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y) #draw a line plot
ax.set_title("total growth over time")# set the plot title
ax.set_xlabel("years since start") #set x axis label
ax.set_ylabel("total growth") #set y axis label


# here is for the next plot but I would like to try how it look like if I have both in one
#the result is there is a second empty plot


# font1={'family':'serif','color':'blue','size':20}
# font2={'family':'monospace','color':'green','size':14}

# fig.ax=plt.subplots(figsize=(5,3))
# ax.plot(x,y)
# ax.set_title("total growth over time",fontdict=font1)
# ax.set_xlabel("years since start",fontdict=font2)
# ax.set_ylabel("total growth",fontdict=font2)

#changed the fonts size and color, appling the lable with the fonts we set

font1={'family':'serif','color':'blue','size':20}
font2={'family':'monospace','color':'green','size':14}

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y)
ax.set_title("total growth over time",fontdict=font1)
ax.set_xlabel("years since start",fontdict=font2)
ax.set_ylabel("total growth",fontdict=font2)

#try customized the marker
fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y,marker="2",color="indigo")

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y,marker="*",color="indigo",linestyle="--",linewidth=2)
#try customize the line styple and line width

#fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y,marker="*",color="indigo",linestyle="--",linewidth=2,markeredgecolor="#fa935495",markerfacecolor="green")
ax.grid(axis='y')

#try the function of markercolor and marker facecolor