# -*- coding: utf-8 -*-
"""visualization class1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfYTi53G0NomCJHR0yGsrNljMPkPh69j
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
import PIL
import requests

np.random.seed(613)
x=np.arange(50)
y=np.random.randint(0,100,50)
fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y)

fig,ax=plt.subplots(figsize=(5,3))
ax.barh(x,y)# used horizontal bars
ax.bar(x,y)#vertical

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y)

fig,ax=plt.subplots(figsize=(5,3))
ax.hist(y)

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y)
ax.set_title("total growth over time")
ax.set_xlabel("years since start")
ax.set_ylabel("total growth")

# font1={'family':'serif','color':'blue','size':20}
# font2={'family':'monospace','color':'green','size':14}

# fig.ax=plt.subplots(figsize=(5,3))
# ax.plot(x,y)
# ax.set_title("total growth over time",fontdict=font1)
# ax.set_xlabel("years since start",fontdict=font2)
# ax.set_ylabel("total growth",fontdict=font2)

font1={'family':'serif','color':'blue','size':20}
font2={'family':'monospace','color':'green','size':14}

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y)
ax.set_title("total growth over time",fontdict=font1)
ax.set_xlabel("years since start",fontdict=font2)
ax.set_ylabel("total growth",fontdict=font2)

fig,ax=plt.subplots(figsize=(5,3))
ax.scatter(x,y,marker="2",color="indigo")

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y,marker="*",color="indigo",linestyle="--",linewidth=2)

fig,ax=plt.subplots(figsize=(5,3))
ax.plot(x,y,marker="*",color="indigo",linestyle="--",linewidth=2,markeredgecolor="#fa935495",markerfacecolor="green")
ax.grid(axis='y')

ax.grid(axis='y')